version: '3.4'

services:
  fly.flight.api:
    image: ${DOCKER_REGISTRY-}flyflightapi
    build:
      context: .
      dockerfile: Fly.Flight.API/Dockerfile
    depends_on: 
        - fly.flight.sqlserver
    networks:
      - fly-network
       
  fly.flight.sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Flyflight!1"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    depends_on:
      - fly.flight.elasticsearch
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - fly-network
  
  fly.flight.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - fly-network

  fly.flight.redis:
    image: redis:7
    ports:
       - "6379:6379"
    restart: always
    networks:
      - fly-network

volumes:
  sql_data:

networks:
  fly-network:
    driver: bridge
